-- Flowwise Sprint 2 Schema Migration: Merchant & Business Account Foundation

CREATE TABLE merchants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_name VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    business_type VARCHAR(100) NOT NULL,
    industry VARCHAR(100) NOT NULL,
    demo_gstin VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE business_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id BIGINT NOT NULL,
    institution_name VARCHAR(255) NOT NULL,
    account_type VARCHAR(50) NOT NULL,
    masked_account_ref VARCHAR(50) NOT NULL,
    current_balance NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    currency VARCHAR(10) NOT NULL DEFAULT 'INR',
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_business_accounts_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id) ON DELETE CASCADE
);

CREATE INDEX idx_business_accounts_merchant_id ON business_accounts (merchant_id);

-- Synthetic Demo Seeds (Explicitly labeled DEMO data)
INSERT INTO merchants (id, business_name, display_name, business_type, industry, demo_gstin, created_at, updated_at)
VALUES 
(1, 'Apex Retail Solutions [DEMO]', 'Apex Retail [DEMO]', 'Private Limited Company', 'Omnichannel Apparel & Goods', 'DEMO-27-GSTIN-0001', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Zenith Electronics Hub [DEMO]', 'Zenith Electronics [DEMO]', 'Partnership Firm', 'Consumer Electronics Wholesale', 'DEMO-29-GSTIN-0002', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'Vanguard Organics [DEMO]', 'Vanguard Organics [DEMO]', 'Sole Proprietorship', 'FMCG & Organics Supply', 'DEMO-19-GSTIN-0003', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO business_accounts (merchant_id, institution_name, account_type, masked_account_ref, current_balance, currency, status, created_at, updated_at)
VALUES 
(1, 'HDFC Bank', 'Current Account', '•••• 4819', 210000.00, 'INR', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'ICICI Bank', 'Reserve Account', '•••• 9021', 74300.00, 'INR', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'State Bank of India', 'Operating Account', '•••• 1154', 40000.00, 'INR', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Axis Bank', 'Current Account', '•••• 7712', 580000.00, 'INR', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'HDFC Bank', 'Operating Account', '•••• 3301', 145000.00, 'INR', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'Kotak Mahindra Bank', 'Current Account', '•••• 8820', 195000.00, 'INR', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'Punjab National Bank', 'Reserve Account', '•••• 2049', 82000.00, 'INR', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
