-- Flowwise Sprint 3 Schema Migration: Transaction Intelligence Ledger

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id BIGINT NOT NULL,
    business_account_id BIGINT NOT NULL,
    transaction_reference VARCHAR(100) NOT NULL UNIQUE,
    transaction_date TIMESTAMP WITH TIME ZONE NOT NULL,
    description VARCHAR(500) NOT NULL,
    amount NUMERIC(15, 2) NOT NULL,
    type VARCHAR(20) NOT NULL,
    category VARCHAR(50) NOT NULL,
    subcategory VARCHAR(50),
    counterparty VARCHAR(255) NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_transactions_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id) ON DELETE CASCADE,
    CONSTRAINT fk_transactions_account FOREIGN KEY (business_account_id) REFERENCES business_accounts (id) ON DELETE CASCADE
);

CREATE INDEX idx_transactions_merchant_id ON transactions (merchant_id);
CREATE INDEX idx_transactions_account_id ON transactions (business_account_id);
CREATE INDEX idx_transactions_date ON transactions (transaction_date);
CREATE INDEX idx_transactions_category ON transactions (category);

-- Synthetic Indian Merchant Transactions Seed (Apex Retail Solutions [DEMO])
INSERT INTO transactions (merchant_id, business_account_id, transaction_reference, transaction_date, description, amount, type, category, subcategory, counterparty, payment_method, status, created_at, updated_at)
VALUES
(1, 1, 'TXN-DEMO-901', CURRENT_TIMESTAMP - INTERVAL '1' HOUR, 'Inventory Settlement - Metro Trade Distributors', 142000.00, 'CREDIT', 'SALES', 'Wholesale Collection', 'Metro Trade Distributors', 'UPI', 'SETTLED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 1, 'TXN-DEMO-902', CURRENT_TIMESTAMP - INTERVAL '1' DAY, 'Freight and Express Logistics Charges', 28400.00, 'DEBIT', 'OPERATIONS', 'Logistics', 'CyberSpace Logistics India', 'NEFT', 'SETTLED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 2, 'TXN-DEMO-903', CURRENT_TIMESTAMP - INTERVAL '3' DAY, 'Bulk Packaging Material Purchase', 64000.00, 'DEBIT', 'INVENTORY', 'Packaging Materials', 'Precision Packaging Pvt Ltd', 'NEFT', 'PENDING', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 1, 'TXN-DEMO-904', CURRENT_TIMESTAMP - INTERVAL '5' DAY, 'Bulk Apparel Order Settlement', 215000.00, 'CREDIT', 'SALES', 'Distributor Sales', 'Zenith Retail Outlets', 'RTGS', 'SETTLED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 1, 'TXN-DEMO-905', CURRENT_TIMESTAMP - INTERVAL '7' DAY, 'UPI QR Collection Settlement', 85000.00, 'CREDIT', 'SALES', 'Retail Collection', 'Kaveri Mart Outlets', 'UPI', 'SETTLED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 'TXN-DEMO-906', CURRENT_TIMESTAMP - INTERVAL '10' DAY, 'Commercial Premises Monthly Lease Rent', 75000.00, 'DEBIT', 'RENT', 'Store Property Lease', 'Commercial Tech Park Realty', 'RTGS', 'SETTLED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 1, 'TXN-DEMO-907', CURRENT_TIMESTAMP - INTERVAL '12' DAY, 'Monthly Electricity and Power Grid Utility Bill', 14200.00, 'DEBIT', 'UTILITIES', 'Electricity Bill', 'State Power Distribution Corp', 'UPI', 'SETTLED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 1, 'TXN-DEMO-908', CURRENT_TIMESTAMP - INTERVAL '15' DAY, 'Monthly Employee Salary Disbursement', 180000.00, 'DEBIT', 'PAYROLL', 'Staff Payroll', 'Monthly Staff Payroll', 'NEFT', 'SETTLED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 2, 'TXN-DEMO-909', CURRENT_TIMESTAMP - INTERVAL '18' DAY, 'GST3B Tax Filing Quarterly Remittance', 42500.00, 'DEBIT', 'TAX', 'GST Payment', 'GST Tax Filing Settlement', 'RTGS', 'SETTLED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 2, 'TXN-DEMO-910', CURRENT_TIMESTAMP - INTERVAL '20' DAY, 'Internal Reserve Account Transfer', 50000.00, 'CREDIT', 'TRANSFER', 'Reserve Fund', 'Internal Reserve Transfer', 'BANK_TRANSFER', 'SETTLED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 1, 'TXN-DEMO-911', CURRENT_TIMESTAMP - INTERVAL '22' DAY, 'Customer Apparel Return Refund', 3500.00, 'DEBIT', 'REFUND', 'Return Processing', 'Customer Refund Claim', 'UPI', 'SETTLED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 1, 'TXN-DEMO-912', CURRENT_TIMESTAMP - INTERVAL '25' DAY, 'Distributor Invoice Payment', 60000.00, 'CREDIT', 'SALES', 'Wholesale Collection', 'Deccan Retail Chains', 'UPI', 'SETTLED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
