-- Sprint 14: Receivables Intelligence Schema Migration

CREATE TABLE receivables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id BIGINT NOT NULL,
    counterparty VARCHAR(255) NOT NULL,
    invoice_reference VARCHAR(100) NOT NULL UNIQUE,
    invoice_amount NUMERIC(15, 2) NOT NULL,
    amount_received NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    outstanding_amount NUMERIC(15, 2) NOT NULL,
    invoice_date TIMESTAMP WITH TIME ZONE NOT NULL,
    due_date TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(50) NOT NULL, -- CURRENT, OVERDUE_1_30, OVERDUE_31_60, OVERDUE_60_PLUS, PAID
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_receivables_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id) ON DELETE CASCADE
);

CREATE INDEX idx_receivables_merchant_id ON receivables(merchant_id);
CREATE INDEX idx_receivables_status ON receivables(status);

-- Seed Synthetic Indian B2B Distributor Invoices Dataset
INSERT INTO receivables (merchant_id, counterparty, invoice_reference, invoice_amount, amount_received, outstanding_amount, invoice_date, due_date, status)
VALUES
(1, 'Reliance Retail Distributors [DEMO]', 'INV-B2B-101', 185000.00, 50000.00, 135000.00, CURRENT_TIMESTAMP - INTERVAL '45' DAY, CURRENT_TIMESTAMP - INTERVAL '15' DAY, 'OVERDUE_1_30'),
(1, 'Vishal Mega Mart Franchise [DEMO]', 'INV-B2B-102', 240000.00, 0.00, 240000.00, CURRENT_TIMESTAMP - INTERVAL '75' DAY, CURRENT_TIMESTAMP - INTERVAL '45' DAY, 'OVERDUE_31_60'),
(1, 'BigBazaar Regional Store [DEMO]', 'INV-B2B-103', 95000.00, 0.00, 95000.00, CURRENT_TIMESTAMP - INTERVAL '110' DAY, CURRENT_TIMESTAMP - INTERVAL '80' DAY, 'OVERDUE_60_PLUS'),
(1, 'Metro Cash & Carry Partner [DEMO]', 'INV-B2B-104', 120000.00, 120000.00, 0.00, CURRENT_TIMESTAMP - INTERVAL '30' DAY, CURRENT_TIMESTAMP - INTERVAL '5' DAY, 'PAID'),
(1, 'Local Kirana Wholesale Hub [DEMO]', 'INV-B2B-105', 78000.00, 28000.00, 50000.00, CURRENT_TIMESTAMP - INTERVAL '15' DAY, CURRENT_TIMESTAMP + INTERVAL '15' DAY, 'CURRENT'),
(1, 'Apex Hypermarket Franchise [DEMO]', 'INV-B2B-106', 160000.00, 0.00, 160000.00, CURRENT_TIMESTAMP - INTERVAL '5' DAY, CURRENT_TIMESTAMP + INTERVAL '25' DAY, 'CURRENT');
